Solution for lection4-logo-and-sprite
js-tasks-ru/htmlcss-20230714_igorgal1234 pull request #16
Opened 2023-08-22 17:58 UTC by ihorhalchenko

2023-08-22 17:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-24 21:37 UTC, GSemikozov requested changes

2023-08-24 21:37 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <use href="/assets/images/icons-sprite.svg#arrow">
так точно работает? не надо указывать относительный путь по типу `../../assets/...`?

2023-08-25 14:08 UTC, ihorhalchenko commented on 03-lection1/02-accordion/index.html
> +            <use href="/assets/images/icons-sprite.svg#arrow">
Да, абсолютный путь работает работает. Проверил Chrome, Opera, Firefox, Edge.

2023-08-26 20:27 UTC, GSemikozov approved these changes

2023-08-26 20:27 UTC, merged