Solution for lection2-histogram
js-tasks-ru/htmlcss-20230714_igorgal1234 pull request #6
Opened 2023-08-01 12:01 UTC by ihorhalchenko

2023-08-01 12:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-01 15:14 UTC, GSemikozov requested changes

2023-08-01 15:14 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  max-width: 304px;
лишнее ограничение

2023-08-01 15:14 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  height: 55px;
лишнее ограничение

2023-08-01 15:14 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  flex-basis: 50%;
лишнее

2023-08-01 15:14 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  flex-basis: 50%;
лишнее. Лучше flex + justify-content: space-between

2023-08-01 15:14 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__link_view-all {
лишний модификатор, у нас всего 1 элемент ссылки

2023-08-01 15:14 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  padding-top: 38px;
margin-top: 39px

2023-08-02 13:03 UTC, ihorhalchenko commented on 04-lection2/01-histogram/histogram.css
> +  max-width: 304px;
тоесть наш компонент будет ограничиваться только родительским блоком но не собой?

2023-08-02 13:03 UTC, ihorhalchenko commented on 04-lection2/01-histogram/histogram.css
> +  height: 55px;
Сделано.

2023-08-02 13:03 UTC, ihorhalchenko commented on 04-lection2/01-histogram/histogram.css
> +  flex-basis: 50%;
Сделано.

2023-08-02 13:04 UTC, ihorhalchenko commented on 04-lection2/01-histogram/histogram.css
> +  flex-basis: 50%;
Сделано. Добавил один div в html и переверстал

2023-08-02 13:04 UTC, ihorhalchenko commented on 04-lection2/01-histogram/histogram.css
> +.histogram__link_view-all {
Сделано.
Это был задел на будущее )))

2023-08-02 13:04 UTC, ihorhalchenko commented on 04-lection2/01-histogram/histogram.css
> +  padding-top: 38px;
Сделано.

2023-08-03 14:08 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  max-width: 304px;
ага

2023-08-03 14:08 UTC, GSemikozov approved these changes

2023-08-03 14:08 UTC, merged