Solution for lection2-skeleton
js-tasks-ru/htmlcss-20230714_igorgal1234 pull request #7
Opened 2023-08-01 13:07 UTC by ihorhalchenko

2023-08-01 13:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-01 15:12 UTC, GSemikozov requested changes

2023-08-01 15:12 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  max-width: 513px;
лишнее

2023-08-01 15:12 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  max-width: 172px;
лучше в процентах

2023-08-01 15:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-02 12:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-02 12:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-02 13:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-02 13:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-02 13:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-02 13:41 UTC, ihorhalchenko commented on 04-lection2/02-skeleton/skeleton.css
> +  max-width: 513px;
Сделано.

2023-08-02 13:41 UTC, ihorhalchenko commented on 04-lection2/02-skeleton/skeleton.css
> +  max-width: 172px;
Сделано.

2023-08-03 14:08 UTC, GSemikozov approved these changes

2023-08-03 14:08 UTC, merged