Solution for laction3-caledar
js-tasks-ru/htmlcss-20230714_igorgal1234 pull request #9
Opened 2023-08-08 18:37 UTC by ihorhalchenko

2023-08-08 18:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-10 11:30 UTC, GSemikozov requested changes

2023-08-10 11:30 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  padding: 28px 30px 40px;
`28 26 32`

2023-08-10 13:38 UTC, ihorhalchenko commented on 05-lection3/03-calendar/calendar.css
> +  padding: 28px 30px 40px;
Исправил.

2023-08-11 13:31 UTC, GSemikozov approved these changes

2023-08-11 13:32 UTC, merged